name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    
    - name: Build binaries
      run: |
        # Create output directory
        mkdir -p dist
        
        # Build for Linux AMD64
        echo "Building linux/amd64..."
        GOOS=linux GOARCH=amd64 go build -o "dist/jupyter-terminal-linux-amd64" -ldflags="-s -w" .
        tar -czf "dist/jupyter-terminal-linux-amd64.tar.gz" -C dist "jupyter-terminal-linux-amd64"
        rm "dist/jupyter-terminal-linux-amd64"
        
        # Build for Linux ARM64
        echo "Building linux/arm64..."
        GOOS=linux GOARCH=arm64 go build -o "dist/jupyter-terminal-linux-arm64" -ldflags="-s -w" .
        tar -czf "dist/jupyter-terminal-linux-arm64.tar.gz" -C dist "jupyter-terminal-linux-arm64"
        rm "dist/jupyter-terminal-linux-arm64"
        
        # Build for Linux ARMv7
        echo "Building linux/arm (v7)..."
        GOOS=linux GOARCH=arm GOARM=7 go build -o "dist/jupyter-terminal-linux-armv7" -ldflags="-s -w" .
        tar -czf "dist/jupyter-terminal-linux-armv7.tar.gz" -C dist "jupyter-terminal-linux-armv7"
        rm "dist/jupyter-terminal-linux-armv7"
        
        # Build for macOS AMD64
        echo "Building darwin/amd64..."
        GOOS=darwin GOARCH=amd64 go build -o "dist/jupyter-terminal-darwin-amd64" -ldflags="-s -w" .
        tar -czf "dist/jupyter-terminal-darwin-amd64.tar.gz" -C dist "jupyter-terminal-darwin-amd64"
        rm "dist/jupyter-terminal-darwin-amd64"
        
        # Build for macOS ARM64 (Apple Silicon)
        echo "Building darwin/arm64..."
        GOOS=darwin GOARCH=arm64 go build -o "dist/jupyter-terminal-darwin-arm64" -ldflags="-s -w" .
        tar -czf "dist/jupyter-terminal-darwin-arm64.tar.gz" -C dist "jupyter-terminal-darwin-arm64"
        rm "dist/jupyter-terminal-darwin-arm64"
        
        # Build for Windows AMD64
        echo "Building windows/amd64..."
        GOOS=windows GOARCH=amd64 go build -o "dist/jupyter-terminal-windows-amd64.exe" -ldflags="-s -w" .
        (cd dist && zip "jupyter-terminal-windows-amd64.zip" "jupyter-terminal-windows-amd64.exe")
        rm "dist/jupyter-terminal-windows-amd64.exe"
        
        # Build for Windows ARM64
        echo "Building windows/arm64..."
        GOOS=windows GOARCH=arm64 go build -o "dist/jupyter-terminal-windows-arm64.exe" -ldflags="-s -w" .
        (cd dist && zip "jupyter-terminal-windows-arm64.zip" "jupyter-terminal-windows-arm64.exe")
        rm "dist/jupyter-terminal-windows-arm64.exe"
        
        # Show what we built
        echo "Build artifacts:"
        ls -la dist/
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*
        draft: false
        prerelease: false
        generate_release_notes: true
        body: |
          ## Installation
          
          Download the binary for your platform and extract it:
          
          **Linux/macOS:**
          ```bash
          # For Intel/AMD systems:
          tar -xzf jupyter-terminal-linux-amd64.tar.gz
          chmod +x jupyter-terminal-linux-amd64
          ./jupyter-terminal-linux-amd64 -url http://localhost:8888
          
          # For ARM64 systems (e.g., newer Raspberry Pi, AWS Graviton):
          tar -xzf jupyter-terminal-linux-arm64.tar.gz
          chmod +x jupyter-terminal-linux-arm64
          ./jupyter-terminal-linux-arm64 -url http://localhost:8888
          
          # For ARMv7 systems (e.g., Raspberry Pi 3/4 32-bit):
          tar -xzf jupyter-terminal-linux-armv7.tar.gz
          chmod +x jupyter-terminal-linux-armv7
          ./jupyter-terminal-linux-armv7 -url http://localhost:8888
          ```
          
          **macOS:**
          ```bash
          # For Intel Macs:
          tar -xzf jupyter-terminal-darwin-amd64.tar.gz
          chmod +x jupyter-terminal-darwin-amd64
          ./jupyter-terminal-darwin-amd64 -url http://localhost:8888
          
          # For Apple Silicon Macs (M1/M2/M3):
          tar -xzf jupyter-terminal-darwin-arm64.tar.gz
          chmod +x jupyter-terminal-darwin-arm64
          ./jupyter-terminal-darwin-arm64 -url http://localhost:8888
          ```
          
          **Windows:**
          ```powershell
          # Extract the zip file and run:
          jupyter-terminal-windows-amd64.exe -url http://localhost:8888
          ```
          
          ## What's in this release?
          
          Check out the automatically generated release notes below for all the changes!
